name: Redfin Spokane Real Estate Scraper

on:
  schedule:
    # Run every 12 hours at 6 AM and 6 PM UTC
    - cron: '0 6,18 * * *'
  workflow_dispatch: # Allow manual triggering

jobs:
  scrape-and-email:
    runs-on: ubuntu-latest
    timeout-minutes: 30 # Prevent runaway jobs
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Run Redfin scraper
      env:
        GMAIL_EMAIL: ${{ secrets.GMAIL_EMAIL }}
        GMAIL_APP_PASSWORD: ${{ secrets.GMAIL_APP_PASSWORD }}
        FORWARDING_EMAIL: ${{ secrets.FORWARDING_EMAIL }}
      run: |
        python redfin_scraper.py --send-email --provider gmail
        
    - name: Upload artifacts on failure (for debugging)
      if: failure()
      uses: actions/upload-artifact@v4
      with:
        name: debug-logs
        path: |
          scout_results_*.xlsx
          scout_results_*.pdf
          test_email_*.html
        retention-days: 7 